openapi: 3.1.0
info:
  version: 1.0.0
  title: Diary app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of diary app
tags:
  - name: Auth
    description: Auth operations.
  - name: Users
    description: Users operations.
  - name: Tasks
    description: Tasks operations.
  - name: Diaries
    description: Diaries operations.
  - name: Weeks
    description: Weeks operations.
servers:
  - url: http://localhost:3000
  - url: https://leleka-backend-1.onrender.com
paths:
  # —Å—Ç–≤–æ—Ä–∏—Ç–∏ –ø—Ä–∏–≤–∞—Ç–Ω–∏–π –µ–Ω–¥–ø–æ—ñ–Ω—Ç –Ω–∞ –æ—Ç—Ä–∏–º–∞–Ω–Ω—è —ñ–Ω—Ñ–æ—Ä–º–∞—Ü—ñ—ó –ø—Ä–æ –ø–æ—Ç–æ—á–Ω–æ–≥–æ –∫–æ—Ä–∏—Å—Ç—É–≤–∞—á–∞
  /users/current:
    get:
      $ref: ../swagger/paths/users/current/get.yaml

      # —Å—Ç–≤–æ—Ä–∏—Ç–∏ –ø—Ä–∏–≤–∞—Ç–Ω–∏–π –µ–Ω–¥–ø–æ—ñ–Ω—Ç –¥–ª—è –æ–Ω–æ–≤–ª–µ–Ω–Ω—è –¥–∞–Ω–∏—Ö –∫–æ—Ä–∏—Å—Ç—É–≤–∞—á–∞
  /users:
    patch:
      $ref: ../swagger/paths/users/patch.yaml

      # —Å—Ç–≤–æ—Ä–∏—Ç–∏ –ø—Ä–∏–≤–∞—Ç–Ω–∏–π –µ–Ω–¥–ø–æ—ñ–Ω—Ç –¥–ª—è –æ–Ω–æ–≤–ª–µ–Ω–Ω—è –∞–≤–∞—Ç–∞—Ä—É –∫–æ—Ä—Å–∏—Ç—É–≤–∞—á–∞
  /users/avatar:
    patch:
      $ref: ../swagger/paths/users/avatar/patch.yaml

  # DIARIES
  # -------------------------------
  /diaries:
    get: # üîπ –û—Ç—Ä–∏–º–∞—Ç–∏ –≤—Å—ñ –∑–∞–ø–∏—Å–∏
      $ref: ../swagger/paths/diaries/get.yaml
    post: # üîπ –°—Ç–≤–æ—Ä–∏—Ç–∏ –Ω–æ–≤–∏–π –∑–∞–ø–∏—Å
      $ref: ../swagger/paths/diaries/post.yaml

  /diaries/{id}:
    patch: # üîπ –†–µ–¥–∞–≥—É–≤–∞—Ç–∏ –∑–∞–ø–∏—Å
      $ref: ../swagger/paths/diaries/{id}/patch.yaml
    delete: # üîπ –í–∏–¥–∞–ª–∏—Ç–∏ –∑–∞–ø–∏—Å
      $ref: ../swagger/paths/diaries/{id}/delete.yaml

  /tasks:
    post:
      $ref: '../swagger/paths/tasks/post.yaml'
    get:
      $ref: '../swagger/paths/tasks/get.yaml'
  /tasks/{id}:
    patch:
      $ref: '../swagger/paths/tasks/{id}/patch.yaml'

  /auth:
    post:
      $ref: ../swagger/paths/auth/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Diary:
      $ref: ../swagger/components/schemas/diaries.yaml
    DiaryInput:
      $ref: ../swagger/components/schemas/diariesInput.yaml
